### ISSUE TITLE
i add items at runtime appendChild

### ISSUE THREAD

**Issue by okbach** [Xarksass/BootstrapSelect#5]
i add items at runtime element.appendChild();
But the filter is not done and there is no and no item can be added

```
  tag = document.createElement("li"); 
  
  tag.className='filter-item items';
  
   tag.setAttribute('data-filter','x');
  
   tag.setAttribute('data-value','x');
```

**Comment by Xarksass** [comment]
Hi,

When the last element has been added to the list you can use the reset method the re-initiate the select (you can do it each time an element is added too if you want)

hope it helps and sorry for this late response.
